### ISSUE TITLE
8-bit immediate error

### ISSUE THREAD

**Issue by paperballs** [JayDDee/cpuminer-opt#112] opened 2018-03-13 00:11 UTC
While running sudo make on Ubuntu 16.04, I'm getting error message: the last argument must be an 8-bit immediate right at the start of this _mm_srli_sil28( hi, n<<2 ), 

https://github.com/JayDDee/cpuminer-opt/blob/157508bd075e28020c642e3f824efc4c810f4863/algo/shavite/sph-shavite-aesni.c#L85

**Comment by JayDDee** [comment] 2018-03-13 01:27
Duplicate of 111.

**Closed by JayDDee** 2018-03-13 01:27 UTC
