### ISSUE TITLE
"--coinbase-addr" setting is broken since v3.11.7

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#241] opened 2020-02-13 13:41 UTC
Works OK in v3.11.5

Please note this is set exactly like the "--help" cli switch output tells us to.

cpuminer-avx2 -a algo_name -t 2 -o http://127.0.0.1:55555 -u rpc_user -p rpc_pass --coinbase-addr=I84KJ8D7DF6HNDSD9SDMDK90SDFS8DF

v3.11.7+ output:
invalid address -- 'I84KJ8D7DF6HNDSD9SDMDK90SDFS8DF'

v3.11.5 output:
Starting miner with AVX2...
[2020-02-13 16:38:11] 24 CPU cores available, 12 miner threads selected.
[2020-02-13 16:38:11] 12 miner threads started, using 'algo_name' algorithm.
...

Any algo, any build, any coinbase address (valid or not).

**Comment by JayDDee** [comment] 2020-02-13 18:06
You seem to have a knack to find the weirdest problems. Thi serror is produced by the CLI
when validating the address fails. I've never touched any of this code I never even knew it
existed so so there is no direct link yo any changes I made in v3.11.6 or 7.

I have no way to test so investigating this will require a lot of help from you. I hope your
comfortable with making some code changes and compiling frequently. I can provide the
debug code but have no way to test it first. So this will become debugging the debug code
before it can beused to debug the real problem.

The error occurs when converting the CB addr to a PK script. This is a very straightforward
where a conversion function is called with the address as its only input.

The address hasn't changed, the conversion function hasn't changed but the conversion
function now fails to convert the address.
 
Troubleshooting will require some debug code be added to collect data. debug code will
need to be added to a woirking version and a broken version for direct comparison.

The first thing is to confirm the conversion function is passed the same data.
Most changes will be adding a call to applog and should be obvious. I may not explain
each change in detail.

cpu-miner.c:2987
`   case 1016:        /* --coinbase-addr */
applog(LOG_INFO,"CB addr: %s",arg);
      pk_script_size = address_to_script(pk_script, sizeof(pk_script), arg);
      if (!pk_script_size) {
         fprintf(stderr, "invalid address -- '%s'\n", arg);
         show_usage_and_exit(1);
      }
`
Also add applo
g calles to every error path in the converter:

address_to script is defined in util.c and calls 2 other functions and does a sha256d round.

Everywhere a fail code is returned needs an applog to identify where the error was detected
and what data caused it to fail. The logs can be added gradually first to address_to_script then to the subroutine that's failing, either b58dec or b58check.

Insert  an applog call just before the error return displaying the bad data. applog works just like
printf if you're familiar with it.

b58dec just returns true or false so just log the fact that it failed there.

b58check returns an int that should be displayed.

Once the subroutine is identified add similar messages to the error path in the appropriate one.

I expect a lot of questions and a lot of back-and-forth to get to the bottom of this. The more
you can figure things out on your own the faster it will go. 

Good luck.

**Comment by JayDDee** [comment] 2020-02-13 18:07
Why doen't code ever display properly?

   case 1016:        /* --coinbase-addr */
      pk_script_size = address_to_script(pk_script, sizeof(pk_script), arg);
      if (!pk_script_size) {
         fprintf(stderr, "invalid address -- '%s'\n", arg);
         show_usage_and_exit(1);
      }

**Comment by YetAnotherRussian** [comment] 2020-02-13 18:20
@JayDDee use <> button to insert a code block in a githib comment ;-)

**Comment by JayDDee** [comment] 2020-02-14 00:08
Good work.

If you change it back to 25 does it work? 
If that works try changing
sizeof(addrbin) 
to 
sizeof(addrbin) - 1

It's used twice, once to set adrver, that one worries me, the other use might not be a problem.

This should force b58 to ignore the last byte and be transparent. If that works the next question
is did it break anything. I'll worry about that later.

I'll have to go back to refresh my memory why I did that. It had to do with support for saplings
but I'm not sure if I just copied blindly or had another reason for that change.

**Comment by JayDDee** [comment] 2020-02-14 04:10
I have no idea why I made that change. The code isn't related to any other changes in that
release and it's only used in that one instance. I have never used that option so I don't know
what would have led me there.

Anyway it looks like a stupid change that had direct negative effects, It will be undone in the 
next release.

**Comment by JayDDee** [comment] 2020-02-14 04:56
Things are getting more complicated. I tracced the change back to 
https://github.com/KotoDevelopers/cpuminer-yescrypt/commit/964c0c42c9dce4a2e87d41bc280db08c8b0eae34#diff-6d7e72ea1ca2b7d0258e568a155084bd

2 years ago with no explanation. 

When I implemented yescryptr8g I tested using a stratum pool, not gbt. I have to assume
it's needed by Koto, otherwise it would have been changed back by now.

This is not good. I don't see an obvious way to support both and i don't have enough knowledge
of the protocol to be creative.

The safest course of action is to revert the change and likely break Koto gbt in the process.

I'm beginning to wonder if this it the tip of the iceberg. There were other changes made to the
protocol for yescryptr8g/koto. GBT may still be broken after I change addrbin back to size 25.

**Comment by YetAnotherRussian** [comment] 2020-02-14 06:45
@JayDDee you may add an "if" statement for this, and bind to an yescryptr8g algo directly. This doesn't look handsomely, but should be safe. I don't think koto code parts would ever be used by any other coins/algos.

**Comment by JayDDee** [comment] 2020-02-14 15:35
Thanks, it's good to know the other changes didn't break anything, it's just the addr size.

If I assume the coinbase addr size is a property of the algo there are some technical and
architectural issues that need to be resolved.

The implementation shouild not violate the gate interface by putting algo exceptions in
common code.

Both the algo and coinbase_addr are CLI args. There is no guarantee the algo arg will be
decoded and known before the coinbase_addr arg is decoded.

The address validation would need to removed from the cli and done at algo registration.
This could solve both issues.

A proper spec would be nice, I hate making assumptions.

**Comment by JayDDee** [comment] 2020-02-14 16:07
I'm going to take a close look at address_script to underestand it better and why the array
size is used as a key factor. That seems like an odd thing to do. It currently affects the
sha256d hash and  addver. 

I'll look for a better way to do it. If the number 25 or 26 is a key parameter it shouldn't be set
based on the size of an array.

**Comment by JayDDee** [comment] 2020-02-14 16:22
I need you to confirm I'm seeing this correctly, it looks too stupid to be believable.

In address_to_script the return variable rv is NEVER SET! 
If the function doesn't return a hard coded 0 on error  it will return the uninitailized rv.

**Comment by JayDDee** [comment] 2020-02-14 16:47
It doesn't look like addrver is actually set by b58check, ity's just extracted from the arg passed
to it.. This also seems like an odd way to do things. Addrver is known before calling b58check,
it does not overwrite bin[0] (addrbin[0]) which was set by b58dec.

I think this needs to be rewritten.

**Comment by JayDDee** [comment] 2020-02-14 17:18
Pending answers to previous question I'm starting to get a clear picture. The data you collect
should confirm it. There are still details to work out but I think I have the big picture.

The size of the local and global addrbin buffer is not important as long as they are both big enough.
26 or larger should work.

b58dec is well written and can handle odd sized buffers and unused buffer space.

b58 check is a mess and should be thrown out, replaced with inline code. The addrver should
be extracted from the decoded address instead of the array size

The bin size needs to determined by means other that the array size, tbd.

addrver (addrbin[0]) shoud be tested before executing sha256d, not after. addrver may be the key
to determine the bin size.

The biggest unknown is what addrver is used by koto. It looks like it shouldn't work with the array
size mismatch. The global array is still 25 bytes so either it works for koto at 25 or it doesn't.
Changing the local array size just corrupted the data for everyone due to the implementation
of b58check.

This leads me to speculate that koto either works with size 25 or was broken before I imported it.

**Comment by JayDDee** [comment] 2020-02-14 18:23
Just as a reminder of the data I'm waiting for:

- which error path was taken, b58dec or b58check (addrver<0)?
- what addrver is used in the general case?

Unknown:

- what addrver is used by koto?

Since @rplant8 is closed source I can't answer that question. But also, because it's closed source,
it's not my problem. 

I will find a solution that is architecturaly sound and tested working in the general case.
It will also avoid the current pitfall. If that also works for Koto then great, otherwise it's
rplant's problem.

**Comment by JayDDee** [comment] 2020-02-14 20:45
Here's a first draft of a proposed solution as desvribed above. Look ity over, tell me what you
think. You can give it a try if you want.

---------------

miner.h:

// define buffer size so both global and local use the same size.extern const int pk_srcipt_buffer_size;

---------------

cpu-miner.c:

const int pk_script_buffer_size = 26;
static unsigned char pk_script[ pk_srcipt_buffer_size ] = { 0 };

-------------

util.c:

size_t address_to_script(unsigned char *out, size_t outsz, const char *addr_b58)
{
   unsigned char addrbin[ pk_script_buffer_size ];
   int addrver;
   size_t rv;

   if (!b58dec(addrbin, sizeof(addrbin), addr))
      return 0;

// for debuggubg only
applog(LOG_INFO,"addrbin[0]= %d",addrbin[0]);

   //  new code
   addrver = addrbin[0];
   if ( addrver < 0 )
      return 0;

//   addrver = b58check(addrbin, sizeof(addrbin), addr);
// start of modified b58check
// bin renamed to addrbin, b58 renamed to addr_b58

   unsigned char buf[32];
   int i;
// here we need the real size, hard code for now;
binsz = 25; 

   sha256d( buf, addrbin, (int) (binsz - 4) );
   if ( memcmp( &addrbin[binsz - 4], buf, 4) )
//      return -1;
      addrver = -1;
   else
   {
      /* Check number of zeros is correct AFTER verifying checksum
       * (to avoid possibility of accessing the string beyond the end) */
      for ( i = 0; addrbin[i] == '\0' && addr_b58[i] == '1'; ++i );

      if ( addrbin[i] == '\0' || addr_b58[i] == '1')
//         return -3;
         addrver = -3;

//   return bin[0];
   }

//  end of modified b58check

// uncghanged...

   if (addrver < 0)
      return 0;
   switch (addrver) {
      case 5:    /* Bitcoin script hash */
      case 196:  /* Testnet script hash */
         if (outsz < (rv = 23))
            return rv;
         out[ 0] = 0xa9;  /* OP_HASH160 */
         out[ 1] = 0x14;  /* push 20 bytes */
         memcpy(&out[2], &addrbin[1], 20);
         out[22] = 0x87;  /* OP_EQUAL */
         return rv;
      default:
         if (outsz < (rv = 25))
            return rv;
         out[ 0] = 0x76;  /* OP_DUP */
         out[ 1] = 0xa9;  /* OP_HASH160 */
         out[ 2] = 0x14;  /* push 20 bytes */
         memcpy(&out[3], &addrbin[1], 20);
         out[23] = 0x88;  /* OP_EQUALVERIFY */
         out[24] = 0xac;  /* OP_CHECKSIG */
         return rv;
   }
}

**Comment by JayDDee** [comment] 2020-02-16 04:46
I did a quick test in v3.11.5 using your command line, only substituting a valid algo,
and it failed, just like with v3.12.3. I therefore can't confirm the problem as described.
Neither v3.11.5 nor 3.12.3 with size 25 works for me.

 ./cpuminer -a x11 -t 2 -o http://127.0.0.1:55555 -u rpc_user -p rpc_pass --coinbase-addr=I84KJ8D7DF6HNDSD9SDMDK90SDFS8DF

         **********  cpuminer-opt 3.11.5  *********** 
     A CPU miner with multi algo support and optimized for CPUs
     with AVX512, SHA and VAES extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

invalid address -- 'I84KJ8D7DF6HNDSD9SDMDK90SDFS8DF'
Try `--help' for more information.

**Comment by JayDDee** [comment] 2020-02-16 19:26
Your address is invalid. I don't how it worked for you in v3.11.5.
I tested back to v3.8.8.1 and it fails every time. But it works with a valid BTC addr in
any version.

I can find no regression and no bug. I see no issue.

This is what I get with a valid BTC addr with no server listening.

./cpuminer -a x11 -t 2 -o http://127.0.0.1:55555 -u rpc_user -p rpc_pass --coinbase-addr=12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

         **********  cpuminer-opt 3.12.4  *********** 
     A CPU miner with multi algo support and optimized for CPUs
     with AVX512, SHA and VAES extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

[2020-02-16 14:19:35] addrver= 0
CPU: AMD Ryzen 7 1700 Eight-Core Processor          .
SW built on Feb 15 2020 with GCC 7.4.0.
CPU features:  AVX2    AES SHA
SW features:   AVX2    AES SHA
Algo features: AVX512 VAES

Starting miner with AVX2 AES...

[2020-02-16 14:19:35] 16 CPU cores available, 2 miner threads selected.
[2020-02-16 14:19:35] Extranonce subscribe: YES
[2020-02-16 14:19:35] HTTP request failed: Failed to connect to 127.0.0.1 port 55555: Connection refused
[2020-02-16 14:19:35] json_rpc_call failed, retry after 10 seconds
[2020-02-16 14:19:35] 2 miner threads started, using 'x11' algorithm.

**Comment by YetAnotherRussian** [comment] 2020-02-17 06:36
That address was a fake. You can use any valid address of ANY of the coins among the supported algos to see it's considered as invalid for now.

I just do not want to post my real addresses here anymore cos I've seen them being tracked and even used in some chats for coin testing. I do not accept this. Sorry if I drove you off the main problem, I just thought you'll see it's a "QWERTYUIOP" address.

I'll provide you the debug info soon, I'm out for a week off my bunch of CPUs and machines, so I'm just a writer for now :)

**Comment by JayDDee** [comment] 2020-02-17 07:36
Fair enough, I wish I would have known that sooner.

I don't think the debug testing I requested is necessary anymore. The situation has changed.
I can reproduce the problem now. I will also have do redo the solution.

Trying diifferent addresses (specifically different coins' addresses) revealed various addrver values.
I don't know if there is a unique addrver for yescryptr8g/koto I could use to sleect the buffer size.

Due to the addr test being done in the CLI code the algo isn't known yet. If I can move the test
to GBT code the algo would have been initialized giving yescryptr8g  the opportunity to set its
custom buffer size before the address is tested.

The solution is based on incomplete information about yescryptr8g but it will acomodate both
configurations transparently.

That's my plan for now unless I get more info about yescryptr8g. 

I'll post more details when they are worked out. Once the addr conversion is moved it will llkeley
be impossible for me to test it properly because I can't make the connection to the deamon.
The miner may not get to the address conversion.

I will also have to workout a test plan.

**Comment by JayDDee** [comment] 2020-02-17 19:00
The primary requirement for a fix is to restore previous behaviour for all agos prior to the
introduction of yescryptr8g without altering the yescryptr8g behaviour.

Socondary requirement is to respect the gate interface and not introduce algo-specific hooks
in common code.

Potential locations of coinbase address test:
- In main after call to register_algo_gate
- At start of longpoll_thread
- At start of gtb_work_decode

gbt_work_decode is rejected because it would  perfom the conversion in every miner thread
and every time work is updated, having a performance impact.

longpool_thread is also rejected because there is no guarantee that longpoll will always be
used solo mining. Iit appears it may be the case but there are exceptions in the code that
imply otherwise.

That leaves main. It avoids the problems of gbt_work_decode and longpoll_thread.
It can also be implemented without testing the algo, just the definition of a coinbase address.

The high level design is is porposed as follows:

1. In the CLI (called early from main)  simply copy the coinbase address arg to a global variable.
The only test would be for syntax.

2. In register_yescryptr8g alter the script_buffer size to 26 from its default of 25.

3. In main after returning from register_algo_gate perform the conversion from address to script
using the script buffer size appropriate for the algo, for yescryptr8g it's 26, for all others algos it's
the default 25.

If you have a chance to review please provide your thoughts.

**Comment by JayDDee** [comment] 2020-02-18 00:31
I have a working porototype. I have also found a Koto address to test with and confirm it works
in v3.12.3. I can therefore fully test the fix.

Test plan:

1. Control testing:
- confirm valid coinbase addresses pass in v3.11.5, prior to adding support for yescryptr8g.
- confirm no other issue with mining using a valid coinbase address in v3.11.5.
- confirm valid coinbase addresses for Koto (yescryptr8g) pass in v3.12.3.
- confirm valid coinbase addresses for other coins fail in v3.12.3.

2. Fix testing:
- test valid coin base addresses for coins other tham KOTO now pass.
- confirm no mining problems with the script after conversion from coinbase address.

3. Regression testing:
- test valid coinbase addresses for Koto still pass.

I can do most of the testing myself. The only thing I can't do is follow through with actual mining,
I only get to the point of trying to connect to the daemon, where it fails.

I leave it up to you do confirm that for your favorite coin(s). For Koto I'll just cross my fingers.

If everything goes well the next news should be a new release.

**Comment by YetAnotherRussian** [comment] 2020-02-18 12:17
Got it. I'll be able to provide some testing for real solo mining. Also, I have lots of different addresses.

Sadly I haven't found any exchanges among those used by me who is able to return address list together with coin algo through API (could be used for a blind brute-force test).

Currently I have 2 fully synced blockhains to test real solo on em. Going further may require significant time costs to sync from scratch even running @ nvme. If I'll be able to find some chains to be small enough to fit into 10gigs of ramdisk, things may go faster.

So I can offer you this:
1) Perform basic tests on your side
2) Publish pre-release
3) I perform address tests
4) I perform solo test on 2 chains
5) (optional) further solo tests
6) Release

I do not insist on step 2, but this should make my tests easier cos I do not have a set up env for cross-compiling, but in Win env I could automate step 3 with ease (sending the output from cpuminer-opt cli to a file or pipe of my written-on-the-knees c# app).

**Comment by JayDDee** [comment] 2020-02-18 17:37
cpuminer-opt-3.12.3.1 is released.

All coinbase address tests passed. Mining tests failed to connect because no daemon was
running.

A successful mining test is if it behaves as it did in v3.11.5. If GBT was broken there with the
same symptoms it's a seperate issue. If it's broken with new symptoms it's a bigger issue.

**Comment by YetAnotherRussian** [comment] 2020-02-19 19:14
I'm back. Currently in the process of testing. ETA is 1-3 days (to find enough blocks). Will comment here.

**Comment by YetAnotherRussian** [comment] 2020-02-19 21:12
The end of the output before we crash:

...
[2020-02-20 00:05:51] anime block 6248104, diff 90.41, net 54.90 MH/s
[2020-02-20 00:06:18] JSON protocol request:
{"method": "getmininginfo", "params": [], "id":8}


* Rebuilt URL to: http://127.0.0.1:25555/
* Found bundle for host 127.0.0.1: 0x2a436d0 [can pipeline]
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 25555 (#0)
* Server auth using Basic with user 'Qwert'
> POST / HTTP/1.1
Host: 127.0.0.1:25555
Authorization: Basic Uz... - **!!! I've cut-off this string !!!**
Accept: */*
Accept-Encoding: deflate, gzip
Content-Type: application/json
Content-Length: 51
User-Agent: cpuminer-opt/3.12.3.1
X-Mining-Extensions: longpoll reject-reason
Expect: 100-continue

* Done waiting for 100-continue
< HTTP/1.1 200 OK
< Date: Wed, 19 Feb 2020 21:06:19 +0000
< Connection: keep-alive
< Content-Length: 235
< Content-Type: application/json
<
C:\cpuminer-opt-3.12.3.1-windows>pause

There may be a json parsing error, or something like that. To figure out, I'll have to rebuild for Linux with some extra debug info... Hope I'll handle that in VM (need to reconfigure the network settings to connect to my local node).

**Comment by JayDDee** [comment] 2020-02-19 22:03
There have been a lot of changes in the output, be careful no to to infer too much from
simple differences in output.

Add --hash-meter to see the traditional thread hashrate reports.

I didn't make any changes that intentionally affected http POST but I did make changes to allow
more continuous hashing without interruption. It had no apparent negative effects on stratum mining
but maybe there were some unknown side effects.

GDB is good for locating the code that crashed, stragetically placed printf is also very useful.

If you went back to 3.9.2.4 does that mean 3.11.5 doesn't work?

I'm thinking this is going to be a long term thing. I suggest going by version starting with the
last known working version, seems to be 3.9.2.4, and find out what broke first and in what version.

I'm suspecting the crash has to do with the statistics I added which rely on stratum info.
I was hoping that solo mining would just report invalid stats but maybe the code wasn't robust
enough to handle invalid data. The timing of the crash may be an indication it's occurring
while submitting a block since it's able to get new blocks and ha.sh them without issue.
If it's not a memory leak it's code that hadn't yet been executed.

You might check to see if your got any unexpected blocks in your wallet, that would confirm
a valid block was submitted before the crash.

Otherwise you can take a look at submit_[lane]_solution in cpu-miner.c, They each call
work_set_target_ratio which gathers all the stats. This might be where it's crashing.
A printf at the start and end of work_set_target_ratio will confirm if a block is being suibmitted
and if it crahed there. 

If the crash is not related to the coinbase issue it deserves its own issue.
Any other problem tied to a unique version should also have a seperate issue opened.

The timing is good for me, there isn't much else to do in cpuiminer at the moment so it's a good
time to focus on stabilizing it after all the recent changes.

I going to put more defensive checks in the stats code to avoid it if not using stratum.

**Comment by JayDDee** [comment] 2020-02-19 22:12
Another thought about the timing of the crash, the summary stats report is output every 5 minutes.
It might be crashing there. cpu-miner.c:report_summary_log

**Comment by JayDDee** [comment] 2020-02-20 04:33
A couple of key releases for the stats feature to help isolate the problem:

v3.9.5: stats introduced
v3.9.8.1: summary report introduced

**Comment by JayDDee** [comment] 2020-02-20 16:39
Issue #247 has been opened to track the ongoing issues with solo mining, in particular in relation 
to the share stats feature.

If the coinbase address validation is now fixed this issue should be closed.

**Comment by YetAnotherRussian** [comment] 2020-02-21 10:08
OK, I'll switch to #244 then.

**Comment by JayDDee** [comment] 2020-02-21 23:05
No reports of problems with coinbase address, closing.

**Closed by JayDDee** 2020-02-21 23:05 UTC
Labels: bug, fix released, regression
