### ISSUE TITLE
[Question] Is CPU affinity working well @ argon2d4096?

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#395] opened 2023-07-10 09:46 UTC
Hi. Got an issue with affinity, something like this:

![image](https://github.com/JayDDee/cpuminer-opt/assets/4670472/fd2300dd-acbf-4de0-b3a7-fcbda40f1679)

avx2-sha-vaes win build, "cpuminer-avx2-sha-vaes.exe -t 4 --cpu-affinity 85 -a argon2d4096"

Same for benchmark mode:

![image](https://github.com/JayDDee/cpuminer-opt/assets/4670472/577363fc-98c0-4e5a-a15f-6b0cdf972637)

This is affecting speed a lot, due to inability for core perf boost to achieve max frequency (>4 cores under heavy load). Any other algo is OK, even argon2d250 and argon2d500. Is there any issues or something specific for this algo? Thanks.

**Comment by YetAnotherRussian** [comment] 2023-07-10 13:50
> I do see a CPU not affined for mining with a heavy load (circled by you in red). What's that? That would a fifth loaded core so would likely affect max clock boost.

This logical core is occupied by cpuminer-opt as well. Thats's the problem.

**Comment by JayDDee** [comment] 2023-07-10 14:09
The only other thread when not mining with stratum or api is workio but it should be mostly idle. Can you do some profiling ro se what the hell it's doing?

**Comment by YetAnotherRussian** [comment] 2023-07-10 14:45
I see the same even @ v3.17.1

> Can you do some profiling ro se what the hell it's doing?

I did, but VS gave no usable info.

**Comment by JayDDee** [comment] 2023-07-10 15:02
workio just handles inter-thread messaging. With -t 1 benchmark it has nothing to do.
I have no explanation for what's going on or why it only affects 1 algo.

**Comment by YetAnotherRussian** [comment] 2023-07-10 15:07
> workio just handles inter-thread messaging. With -t 1 benchmark it has nothing to do.
> I have no explanation for what's going on or why it only affects 1 algo.

I'm not competent in Argon2 algo, but I see some "parallelism" settings in scanhash_argon2d4096. Is there anything different between Agon2d4096 and Argon2d500?

**Comment by JayDDee** [comment] 2023-07-10 15:33
That threading code is a mess but is not used because threads/parallelism is always 1.
I tested with a log in core.c:fill_memory_blocks_mt that never gets hit.

**Comment by YetAnotherRussian** [comment] 2023-07-10 15:46
I can profile on my machine if you have the ability to build a single win build with the -pg option and share it. As I see, there's no difference between sse2 or avx2-sha-vaes builds, any one is suitable to reproduce.

**Comment by JayDDee** [comment] 2023-07-10 17:18
Have you tried sysinternals process monitor?

**Comment by YetAnotherRussian** [comment] 2023-07-10 17:56
> Have you tried sysinternals process monitor?

It's functionality is built onto Process Explorer, or vice versa. Lots of statup events, no real-time.

**Comment by JayDDee** [comment] 2023-07-10 18:40
There is a clear performance difference with argon2d4096 on Windows.
I have 2 6700K CPUs, one with Windows, the other with Linux.
With -t 1 and default affinity the Linux hashrate is double. With argon2d500 it's the same on both CPUs.
I also tried argon2d4096 -t 2 --cpu-affinity 5 but I didn't see the rogue CPU load. It had 2 cores at 50% and the other 2 idle but with low hashrate.
The only significant difference is argon2d4096 uses the raw hash function with the parameters passed as function arguments.
I don't see how that should make a difference on Windows.

**Comment by JayDDee** [comment] 2023-07-10 19:36
> I've just put "exit(2)" right after submitting block at line 1216 in cpu-miner.c and -pg switch to build.sh script. It's strange there's no gmon.out generated... Have you ever used this method?

I know nothing. I was only interested in profiling to identify the rogue thread. Since I can reproduce the problem without the riogue thread it's moot.

**Comment by JayDDee** [comment] 2023-07-11 17:46
I did a little more testing comparing both CPUs. The actual performance penalty is  around 33%, all cores at 100% occupancy, same clocks and similar temperatures. This suggests both CPUs were working equally hard.
I reconfirmed argon2 threading is not being used by globally disabling it at compile time. It made no difference.

The only differences between argon2d500 and argon2d4096 are:
- the unique parameters that define the algo,
- the code path from scanhash to hash_ctx, which are just wrapper functions for hard coding selected parameters.

The only difference in argon2d generic code between Windows and Linux is in the threaded code that was disabled.

The paradox is why performance of argon2d4096 is different on Windows vs Linux while argond2d500 performance is identical on both OSs.

I have no leads at this time.

**Comment by JayDDee** [comment] 2023-07-18 21:00
I did a little test, tinkering is more like it. I swapped the mcost params of argon2d500 and argon2d4096 so they would each run with their own code and parametrers except for mcost.

`4096 ref    Linux = 2190, Win = 1300`
`4096 mod Linux = 40k, Win = 39k`
`500 ref      Linux = 16k, Win = 15.7k`
`500 mod   Linux = 970, Win = 785`

Simply changing mcost makes the difference. This eliminates the miner code as the cause but perhaps something in the memory interface between mingw and Windows.

**Comment by YetAnotherRussian** [comment] 2023-07-21 21:30
I did another test @ Windows:
cpuminer-avx2 -a argon2d4096 -t 6 => ~1865h/s
cpuminer-avx2 -a argon2d4096 -t 6 afffinity to 0,2,4,6,8,10 => ~2350h/s
cpuminer-avx2 -a argon2d4096 -t 1, 6 instances (no affinity) => ~455*6=2730h/s
cpuminer-avx2 -a argon2d4096 -t 1, 6 instances (afffinity to 0,2,4,6,8,10) => ~460*6=2760h/s

So it may be something that is slowing down threading, or maybe thread syncing.

**Comment by JayDDee** [comment] 2023-07-21 23:30
> So it may be something that is slowing down threading, or maybe thread syncing.

But it doesn't affect argon2d500 or any other algo.

I did another test of Win vs Lin with argon2d4096 while changing the mcost parameter. At mcost=896 the hashrate is the same on both OSs, at mcost>=1024 it diverges. That is consistent with argon2d500 not being affected (mcost=500).

Your multi-instance test looks interesting but I don't think it's related. The main reason to use affinity is to avoid hyperthreading two miner threads on the same physical core. I have no idea why 6 separate instances would have a higher hashrate than one instance with 6 threads.

**Comment by JayDDee** [comment] 2023-09-12 20:44
No new developments, closing.

**Closed by JayDDee** 2023-09-12 20:44 UTC
