### ISSUE TITLE
Crash on startum share reject (v. 3.20.3+)

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#399] opened 2023-09-05 16:09 UTC
Sad week full of bugs :(

v. 3.20.0 is working OK, sadly it seems to be the latest one which is unaffected
v. 3.20.3+ got a crash

Earlier versions, e.g. from v3.17.1:

![image](https://github.com/JayDDee/cpuminer-opt/assets/4670472/fed48707-1110-4803-926a-0362489d19c7)

From 3.23.0:

![image](https://github.com/JayDDee/cpuminer-opt/assets/4670472/982790bb-5f16-4bff-8e8c-a4a4e74a388e)

I see nothing strange here, hmmm

I've tried to emulate rejects @ random third-party pool using wrong algo, but it works!

**Comment by YetAnotherRussian** [comment] 2023-09-05 16:49
UPD:. Heh, it seems to be a bug in my sofware, as the job changes in between notify and submit (pool side). I call some kinda method that modifies the current job which miners are still working on... I'll have to fix this myself.

The question is - why cpuminer-opt is crashng in the latest versions?

I also use closed-source mining software, it doesn't crash.

**Comment by JayDDee** [comment] 2023-09-05 17:28
It looks like it's crashing on the reject reason. That code was last changed in 3.20.2 and modified the logging of low difficulty shares. Immediately following the Rejected log the reason text is parsed for "difficulty" to report the share & target difficulty instead of the hash values.
Everything points to that code but I don't see why it crashes. The reason text is clearly "low difficulty share" as displayed in the protocol log and there's no other apparently risky code.

Coincidentally I saw some low diff shares during testing this week, no crash.

**Comment by JayDDee** [comment] 2023-09-06 15:08
This is getting weird. I can prevent the low difficulty shares by reverting the sha256 optimization but I still have no idea why they're happening. 
The crash trying to report a low diff reject is also a mystery, I don't see any crashes in my testing.

**Comment by YetAnotherRussian** [comment] 2023-09-06 17:51
Please leave this one for a bit, I'll make gdb report in a day and a half.

**Comment by JayDDee** [comment] 2023-09-06 18:52
I suggest crash testing with -t 1 to avoid any parallel output iconfusion.

I may have found the bug causing the low diff shares with sha256*. I need to do a lot more testing.

**Comment by JayDDee** [comment] 2023-09-11 02:35
I'm ready with a fix for #344. The fix is better than I expected.

If nothing comes up that addresses your current issues I'll go ahead with the release.

**Comment by JayDDee** [comment] 2023-09-17 18:25
Unexpectedly I'm planning yet another release in the next couple of days. If you have anything that needs to be addressed let me know.

**Comment by YetAnotherRussian** [comment] 2023-09-17 19:04
You've made this realease faster than I got home to gdb ;)

So I've started with cloning a fresh release from the repo and I can confirm there's no low diff shares for SHA256D anymore...

But, the first thing I've tried was using -a sha256dt for a sha256d stratum pool ith the latest release. I got this:

![image](https://github.com/JayDDee/cpuminer-opt/assets/4670472/68615e4c-e93c-4f42-a815-ba5bdf4d1e6f)

So you could easily emulate a crash using wrong algo at a low stratum diff

**Comment by JayDDee** [comment] 2023-09-17 20:22
At first glance it looks like yet another alignment issue, note "__strchr_avx2".
Try compiling with "-O2" to see if it still crashes.

I've been doing a lot of testing with all sha256 d/t/dt but your crash is in protocol code so it's not relevant.
The reason pointer returned by JSON was likely not aligned and crashed due to the compiler's avx2 optimization.
I'll have to search to see if it's an internal thing or if it was from a callback.

Editiorial: if the compiler can't guarantee alignment of a pointer it should not vectorize it.

**Comment by JayDDee** [comment] 2023-09-18 03:25
I'm stuck right now. The best I can come up with is a debug log to display the reason pointer to confirm it's alignment:

cpuminer:share_result
`if ( opt_debug ) applog(LOG_NOTICE,"reason: %p, %s", reason, reason );`
`         if ( strstr( reason, "difficulty" ) )`
`           applog2( LOG_MINR, "Share diff: %.5g, Target: %.5g",`
`                               my_stats.share_diff, my_stats.target_diff );`

**Comment by YetAnotherRussian** [comment] 2023-09-18 05:28
> Try compiling with "-O2" to see if it still crashes.

No changes, even with -O1

I'll look into "#pragma"s that might be able to disable "-ftree-vectorize" for selected code segments. That may be the only way.

As I see from GCC's docs "-ftree-vectorize" is enabled for "-O3" but disabled for "-O2"

**Comment by JayDDee** [comment] 2023-09-18 15:33
The crash is in the string library so it may still use vectorized code even if the application is compiled without.
The same thing occurs with Pooler ASM. it will use AVX2 if the CPU supports it even if compiled without it.
(It would be nice if I could do that with cpuminer-opt, only one binary file would be required to support all architectures but it means reqriting all th ehash code in ASM.)

I compiled cpu-miner.c to get an ASM listing using objdump. It's hard to read, the target names of function calls weren't displayed so I couldn't identify the call to strstr. There was some use of xmm registers but the only use of ymm was an unaligned load.
All the vector code seemed related to floating point, nothing string related.

It's looking like solving the root problem is out of reach of cpuminer. I can remove the condition that's causing the crash and display the diff for every reject. Displaying useful info for rejects is still a work in progress but it looks like keying on the reject reason text to choose what to display is not going to work.

I could still try the local aligned buffer workaround but it's still trial and error. Can you try it so I know it works before I make it permanent? If not I'll remove the condition and display diff for all rejects.

**Comment by YetAnotherRussian** [comment] 2023-09-19 19:22
> Another thing you coud try is build without AVX2, just AVX & AES:
> `CFLAGS="-O3 -march=corei7-avx -maes -Wall -fno-common" ./configure --with-curl`

No that doesn't work, as any of your prebuild binaries from sse2 to avx2-sha-vaes crash as well

> Try with --quitet, without --debug. That will skip the string test as well as displaying the reason log.

That helped! And I finally got some info on a crash reason:

![image](https://github.com/JayDDee/cpuminer-opt/assets/4670472/01efe15b-690f-4611-a89e-210c25641ec1)

Seems that without --quiet option cpuminer-opt tries to show the reject reason and in that moment it gets "Accepted" (or empty reason) result for a share which was already rejected. This maybe leads to attempt to handle already null or empty reason?

That's from the server logs:

![image](https://github.com/JayDDee/cpuminer-opt/assets/4670472/a0a0d391-f372-4806-a28e-d61bb4a62e53)

So any other mining software (wildrig, srbminer, cryptodredge - others untested) just some kinda kiks or skips those incoming messages and forces a share to be rejected.

I've already fixed that and I've left that old version. If you're interested, may fix and retest. If not, you can close :)

**Comment by JayDDee** [comment] 2023-09-19 20:33
I think I see it now in the screenshot in the OP. The miner is getting 2 responses for every submitted share. That will mess things up pretty good. It's part of the lack of synchronization between submitted shares and their respective results response.  They aren't evenhandled by the same thread, mining threads submit, stratum thread receives responses. If responses come out of order that will mess things up too. It's all very fragile, one lost message due to a network glitch and the stats queue gets corrupt.
This lack of synchronization is also why I can't display the actual hash that corresponds to a share when it's rejected.

The crash looks like a mutex problem opening a window between checking the reason pointer for NULL and using it allowing it to be overwritten by the second response. I don't like mutex, it slows thing down, I don't want to add more for an externally created problem.

Since this is caused by receiveing bad data and the known problems this can cause, it's closing time.

Nevertheless the log will be changed to display difficulty for all rejects without scanning the reason text.
I believe printf can handle NULL strings even though it seems strstr can't.

**Closed by JayDDee** 2023-09-19 20:33 UTC
