### ISSUE TITLE
[solo mode] "Block solved" is not always printed off

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#329] opened 2021-06-21 07:51 UTC
Hi. Solo mode output for a prolonged period of time looks a little bit strange:

In solo mode I got 100% accepted:

![image](https://user-images.githubusercontent.com/4670472/122725276-7d4ee700-d27d-11eb-8d08-e76fffb414a7.png)

But the stats report and immediate output (on block acceptance) shows that not all of them are blocks, which is impossible.

I'm unsure about the reason, but feel free to ask for any debug info, if needed. 

Or, maybe, this should be hardcoded: if it's getwork/gbt, then any accepted share should be forcibly considered as a solved block.

Some additional info: latest build, argon2d, Windows (any ver. really), multiple threads, gigabit lan, rpc server on a performance 4-core cpu

Thanks.

**Comment by JayDDee** [comment] 2021-06-21 12:21
BLOCK SOLVED is based on the submitted share diff >= network diff. The net diff for block 4966696 is .00027 but the non-block
share is only .00025. Did the wallet accept the blocks not reported by the miner? 

I noticed that a new block with a lower diff was emmitted immediately after the share was submitted. The share diff would have
been a valid block solution for 4956297. Can you confirm the wallet reports the same block and diff as the miner or did share
118 actually solve the next block?

You can add -D to get the actual hash value and target used to decide whether to submit the share. Since the miner
submitted the share it thought it passed the test. The hash value should be <= target to be submitted.

**Comment by YetAnotherRussian** [comment] 2021-06-21 14:14
> Can you confirm the wallet reports the same block and diff as the miner or did share
> 118 actually solve the next block?

Well, in short words, yes:
Block was submitted & accepted (no "BLOCK SOLVED" info):
![image](https://user-images.githubusercontent.com/4670472/122776063-6c20cd00-d2b3-11eb-9ad9-7a19fe4b053a.png)

Reward payed & enough confirmations passed for that block:
![image](https://user-images.githubusercontent.com/4670472/122776328-ac804b00-d2b3-11eb-955d-392b4de561a4.png)

No other blocks found in this period of time as well.

-D option was set, will take some time to collect data

**Comment by JayDDee** [comment] 2021-06-21 15:16
I don't see the block number? Did the wallet confirm block 4956658 or 4956659?

I also don't see the net diff for block 4956658. Was it higher than 4956659? Was it higher that the share diif for share 134?

**Comment by YetAnotherRussian** [comment] 2021-06-21 17:27
> I don't see the block number? Did the wallet confirm block 4956658 or 4956659?

Sorry, this info cannot be found in the wallet...

UPDATE: got some debug data:

**### 1) The case we found a block, it got accepted, it was logged like a block:**

[2021-06-21 18:14:30] GBT new work received in 1.00 ms[0m
[2021-06-21 18:14:30] Threads restarted for new work.[0m
[2021-06-21 18:14:32] Threads restarted for new work.[0m
[2021-06-21 18:14:32][01;37m 7 Submitted Diff 0.0005752, Block 4956884, Ntime d4acd060[0m
[2021-06-21 18:14:32] Thread 0, Nonce 99010000, Xnonce2 Argon2d[0m
[2021-06-21 18:14:32] Data[0:19]: 0408a324 c129ae0b affe8072 7ac21fde f0d9ad60 f61d12a0 91784839 0173a85b eb0f6af5 7a8085d0[0m
[2021-06-21 18:14:32]           : d2d480bd 08d03be9 c8245b7b e249aec9 af1bf20f ead36f95 b8ec81b0 d4acd060 79e20c1e 99010000[0m
[2021-06-21 18:14:32] Hash[7:0]: 000006ca 8a2c622e 1fac1e25 44847549 6af9a743 38615d16 6d9d8d1b 27662d73[0m
[2021-06-21 18:14:32] Targ[7:0]: 00000ce2 79000000 00000000 00000000 00000000 00000000 00000000 00000000[0m
[2021-06-21 18:14:32][01;37m 7 [01;37m[32mA6 [01;37mS0 [01;37mR1 [01;37m[35mBLOCK SOLVED 6[01;37m, 185.790 sec (13ms)[0m
                      Diff 0.0005752, Block 4956884[0m
[2021-06-21 18:14:32] Mining info: diff 0.00030317, net_hashrate 4249147687814.563000, height 4956884[0m
[2021-06-21 18:14:32] GBT new work received in 16.00 ms[0m
[2021-06-21 18:14:32][36m New Block 4956885, Net Diff 0.00030317, Ntime d6acd060[0m
                      Miner TTF @ 1804.58 h/s 12m01s, Net TTF @ 4249.15 Gh/s 0m00s[0m
[2021-06-21 18:14:32] Threads restarted for new work.[0m
[2021-06-21 18:14:37] Mining info: diff 0.00030317, net_hashrate 4249147687814.563000, height 4956884[0m
...
[CUT-OFF PART]
...

                     [01;37m Periodic Report     5m00s        45m26s[0m
                      Share rate        0.20/min     0.15/min[0m
                      Hash rate       4336.74h/s   3797.58h/s   (1827.17h/s)[0m
                      Lost hash rate     0.00h/s    477.66h/s[0m
                      Submitted             1            7[0m
                      Accepted              1            6[0m
                      Rejected              0            1[0m
                      Blocks Solved         1            6[0m
                      Hi/Lo Share Diff  0.0052339 /  0.00042185[0m


**### 2) The case we found a block, it got accepted, but logged like a block:**

[2021-06-21 18:32:43] Mining info: diff 0.00030317, net_hashrate 4082687570475.483900, height 4956892[0m
[2021-06-21 18:32:43] GBT new work received in 1.00 ms[0m
[2021-06-21 18:32:43] Threads restarted for new work.[0m
[2021-06-21 18:32:48] Mining info: diff 0.00030317, net_hashrate 4082687570475.483900, height 4956892[0m
[2021-06-21 18:32:48] GBT new work received in 1.00 ms[0m
[2021-06-21 18:32:48] Threads restarted for new work.[0m
[2021-06-21 18:32:54] Threads restarted for new work.[0m
[2021-06-21 18:32:54][01;37m 8 Submitted Diff 0.00024822, Block 4956893, Ntime 1eb1d060[0m
[2021-06-21 18:32:54] Thread 11, Nonce 4eaeaaea, Xnonce2 main[0m
[2021-06-21 18:32:54] Data[0:19]: 0408a324 7020a4e4 7ef8772c c3572896 92031ea5 32a4a310 58ce7f75 114790fe ae093ec1 bfa82b04[0m
[2021-06-21 18:32:54]           : 174b428b 29d5f185 1a212286 d861e17b 2158aa58 5dea39f0 7786d5a8 1eb1d060 ffff0f1e 4eaeaaea[0m
[2021-06-21 18:32:54] Hash[7:0]: 00000fbc b004ebb5 4a597a93 74895a55 03164a20 9ac129b9 d4aa1530 e8136a4c[0m
[2021-06-21 18:32:54] Targ[7:0]: 00000fff ff000000 00000000 00000000 00000000 00000000 00000000 00000000[0m
[2021-06-21 18:32:54][01;37m 8 [01;37m[32mAccepted 7 [01;37mS0 [01;37mR1 [01;37mB6[01;37m, 1101.208 sec (23ms)[0m
                      Diff 0.00024822, Block 4956893[0m
[2021-06-21 18:32:54] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:32:54] GBT new work received in 16.00 ms[0m
[2021-06-21 18:32:54][36m New Block 4956894, Net Diff 0.00024414, Ntime 24b1d060[0m
                      Miner TTF @ 1833.10 h/s 9m32s, Net TTF @ 3969.15 Gh/s 0m00s[0m
[2021-06-21 18:32:54] Threads restarted for new work.[0m
[2021-06-21 18:32:59] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:32:59] GBT new work received in 1.00 ms[0m
[2021-06-21 18:32:59] Threads restarted for new work.[0m
[2021-06-21 18:33:04] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:04] GBT new work received in 2.00 ms[0m
[2021-06-21 18:33:04] Threads restarted for new work.[0m
[2021-06-21 18:33:09] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:09] GBT new work received in 1.02 ms[0m
[2021-06-21 18:33:09] Threads restarted for new work.[0m
[2021-06-21 18:33:14] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:14] GBT new work received in 1.00 ms[0m
[2021-06-21 18:33:14] Threads restarted for new work.[0m
[2021-06-21 18:33:19] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:19] GBT new work received in 1.00 ms[0m
[2021-06-21 18:33:19] Threads restarted for new work.[0m
[2021-06-21 18:33:24] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:24] GBT new work received in 2.00 ms[0m
[2021-06-21 18:33:24] Threads restarted for new work.[0m
[2021-06-21 18:33:29] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:29][36m argon2d4096: 127.0.0.1:54321[0m
                     [01;37m Periodic Report     5m00s        1h00m[0m
                      Share rate        0.20/min     0.13/min[0m
                      Hash rate       3483.59h/s   3207.02h/s   (1833.10h/s)[0m
                      Lost hash rate     0.00h/s    288.54h/s[0m
                      Submitted             1            8[0m
                      Accepted              1            7[0m
                      Rejected              0            1[0m
                      Blocks Solved         0            6[0m
                      Hi/Lo Share Diff  0.0052339 /  0.00024822[0m
[2021-06-21 18:33:29] GBT new work received in 1.00 ms[0m
[2021-06-21 18:33:29] Threads restarted for new work.[0m
[2021-06-21 18:33:34] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:34] GBT new work received in 1.00 ms[0m
[2021-06-21 18:33:34] Threads restarted for new work.[0m
[2021-06-21 18:33:39] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:39] GBT new work received in 2.00 ms[0m
[2021-06-21 18:33:39] Threads restarted for new work.[0m
[2021-06-21 18:33:44] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:44] GBT new work received in 1.00 ms[0m
[2021-06-21 18:33:44] Threads restarted for new work.[0m
[2021-06-21 18:33:49] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:49] GBT new work received in 1.00 ms[0m
[2021-06-21 18:33:49] Threads restarted for new work.[0m
[2021-06-21 18:33:54] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:54] GBT new work received in 1.00 ms[0m
[2021-06-21 18:33:54] Threads restarted for new work.[0m
[2021-06-21 18:33:59] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:33:59] GBT new work received in 2.00 ms[0m
[2021-06-21 18:33:59] Threads restarted for new work.[0m
[2021-06-21 18:34:04] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:34:04] GBT new work received in 1.00 ms[0m
[2021-06-21 18:34:04] Threads restarted for new work.[0m
[2021-06-21 18:34:09] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:34:09] GBT new work received in 1.00 ms[0m
[2021-06-21 18:34:09] Threads restarted for new work.[0m
[2021-06-21 18:34:14] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:34:14] GBT new work received in 1.00 ms[0m
[2021-06-21 18:34:14] Threads restarted for new work.[0m
[2021-06-21 18:34:19] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:34:19] GBT new work received in 2.00 ms[0m
[2021-06-21 18:34:19] Threads restarted for new work.[0m
[2021-06-21 18:34:24] Mining info: diff 0.00024414, net_hashrate 3969149518085.090800, height 4956893[0m
[2021-06-21 18:34:24] GBT new work received in 2.00 ms[0m
[2021-06-21 18:34:24] Threads restarted for new work.[0m
[2021-06-21 18:34:29] Mining info: diff 0.00024414, net_hashrate 4163322918242.616200, height 4956894[0m
[2021-06-21 18:34:29] GBT new work received in 1.16 ms[0m
[2021-06-21 18:34:29][36m New Block 4956895, Net Diff 0.00024414, Ntime 83b1d060[0m
                      Miner TTF @ 1818.29 h/s 9m36s, Net TTF @ 4163.32 Gh/s 0m00s[0m
[2021-06-21 18:34:29] Threads restarted for new work.[0m

**Comment by YetAnotherRussian** [comment] 2021-06-21 17:36
Will get some more consistent logs soon, as I got a total blackout for around 1 hour, so the ones above may be messy in terms of 1-hour report period (the tee tool from GnuWin32 tools just appended some new logs into an older ones). Will give a full .txt

**Comment by JayDDee** [comment] 2021-06-21 19:54
I think I've found the bug. The target diff is not being updated correctly for the stats. It's only a GBT problem and it doesn't
affect mining. The only symptom is that solved blocks are reported by the miner only as accepted.

**Comment by JayDDee** [comment] 2021-06-23 16:47
I noticed another issue, the net hashrate seem way too high. This results in a zero second TTF estimate yet blocks are emitted
aproximately every 20 seconds. The net hadshrate is provided by the RPC server by the get_mininginfo method and is
reported on the new block log. The value can be confirm by adding the -P option to capture the raw RPC response.

Can you add -P to see if the numbers match? Can you also try to determine the net hashrate by other means
such from any pools that report it? I want to make sure it's not a miner problem.

**Comment by JayDDee** [comment] 2021-06-23 16:57
Regarding the original issue it looks like the stats were based on the previous block's net diff. Net diff isn't used for verifying
hash, the actual hash target is used, therefore mining wasn't directly affected, only the stats.

The only effect of the incorrect diff was in the determination of the hash being good enough to solve a block.
If the previous block had a higher diff and the submitted hash was between the old diff and new diff the hash would
be reported as only being good eough for an eccepted share, not a full block.

Had mining been affected you would have seen a lot of stale shares.

I have a fix for it but I'll wait for more infor about the net hashrate issue.

**Comment by YetAnotherRussian** [comment] 2021-06-23 19:36
> I noticed another issue, the net hashrate seem way too high

This is not an issue, or at least not a miner issue. This nethash value is the total nethash for a multi-algo netwok (that includes ASIC algorithms with the appropriate hashrate, something like "algo1 + algo2 + ... + algo n" hashrate) while the JSON-RPC server is configured to provide Argon2d "work" for cpuminer-opt. Diff value and TTF are reported correctly. I haven't seen a multi-algo solo mining which behaves not like this.

**Comment by JayDDee** [comment] 2021-06-23 22:14
Thanks for the explanation about the hashrate. I agree there is nothing to be done in the miner.

**Comment by JayDDee** [comment] 2021-06-24 02:00
cpuminer-opt-3.16.4 is released. It has changes to GBT code that has not been properly tested. Please test and report any
problems.

**Comment by YetAnotherRussian** [comment] 2021-06-24 09:33
Well, as for now I cannot confirm this one is fixed in 3.16.4...

![image](https://user-images.githubusercontent.com/4670472/123239492-15500900-d4e8-11eb-8c77-314cfa8cba16.png)
![image](https://user-images.githubusercontent.com/4670472/123239570-2ac53300-d4e8-11eb-8239-da334dd34dc0.png)
![image](https://user-images.githubusercontent.com/4670472/123239641-3fa1c680-d4e8-11eb-92f9-f99547f63228.png)
![image](https://user-images.githubusercontent.com/4670472/123239739-56481d80-d4e8-11eb-9b83-2871113d63c4.png)

Stay tuned, I'll colect some data with -D

**Comment by YetAnotherRussian** [comment] 2021-06-24 10:57
New log
[cpuminer_log2.zip](https://github.com/JayDDee/cpuminer-opt/files/6708606/cpuminer_log2.zip)

**Comment by JayDDee** [comment] 2021-06-24 17:31
I may have found something that needs further investigation at time 13:34:27 in the log file, extracted and anotated below.
It looks like a synchronization problem, a solution for a new block was submitted before the new block was logged and before
the stats were updated for the new block.

[2021-06-24 13:34:22] Mining info: diff 0.00039259, net_hashrate 2829971517045.932100, height 4961207
---> last mining info before submit, block 207, dif = .00039

[2021-06-24 13:34:22] GBT new work received in 1.61 ms
[2021-06-24 13:34:22] Threads restarted for new work.
---> restart for block 207

[2021-06-24 13:34:27] Threads restarted for new work.
---> restart for block 208? No mininginfo or new_block log??? No "GBT new work received" log either

[2021-06-24 13:34:27] 4 Submitted Diff 0.00024479, Block 4961208, Ntime b05fd460
---> hash submitted for block 208

[2021-06-24 13:34:27] Thread 10, Nonce 155855d5, Xnonce2 main
[2021-06-24 13:34:27] Data[0:19]: 0408a324 47ec6e53 51e56837 91afe6b4 c89472eb 8c190d24 c0482ad2 768df04e 1b2dacf3 fbe7ac84
[2021-06-24 13:34:27]           : 833a2fdf 19cc35c6 aac4a654 e368509c b29f475f 34a0c552 4248baab b05fd460 ffff0f1e 155855d5
[2021-06-24 13:34:27] Hash[7:0]: 00000ff5 14968649 a1cdeaad 62ccace6 9472b455 187c2ff8 d551aa43 ea3479fb
[2021-06-24 13:34:27] Targ[7:0]: 00000fff ff000000 00000000 00000000 00000000 00000000 00000000 00000000
[2021-06-24 13:34:27] 4 (null)Accepted 3 (null)S0 (null)R1 (null)B2#[01;37m, 179.724 sec (14ms)
                      Diff 0.00024479, Block 4961208
---> hash for block 208 is valid but stats calculated using diff from block 207

[2021-06-24 13:34:27] Mining info: diff 0.00024414, net_hashrate 2830616464680.111800, height 4961208
----> mininginfo finaly logged for block 208, with lower diff .00024

[2021-06-24 13:34:27] GBT new work received in 17.00 ms
[2021-06-24 13:34:27] New Block 4961209, Net Diff 0.00024414, Ntime b55fd460
                      Miner TTF @ 1728.50 h/s 10m06s, Net TTF @ 2830.62 Gh/s 0m00s
[2021-06-24 13:34:27] Threads restarted for new work.
---> block 209 received and logged

**Comment by YetAnotherRussian** [comment] 2021-06-24 18:04
Btw, that's what you've asked before in details (huge nethash because of sha256, scrypt & groestl):

[2021-06-24 21:00:13] JSON protocol response:
{
   "error": null,
   "result": {
      "networkhashps": 842823331141.94275,
      "difficulty_lyra2re2": 0.006680133963519649,
      "errors": "",
      "currentblocktx": 0,
      "difficulty": 0.0002441371325370145,
      "pow_algo": "Argon2d",
      "blocks": 4961565,
      "pow_algo_id": 4,
      "difficulty_argon2d": 0.0002441371325370145,
      "currentblocksize": 1000,
      "difficulty_sha256d": 1497264119.0667591,
      "difficulty_scrypt": 410512.93282714993,
      "difficulty_groestl": 332.15125717679672,
      "difficulty_yescrypt": 0.0022614096371972232,
      "pooledtx": 0,
      "chain": "main"
   },
   "id": 8
}

**Comment by JayDDee** [comment] 2021-06-25 05:36
I've found the problem, it's get_mininginfo. It's data is always for the previous block so the net_diff is always one block behind.
The problem is it overwrites the global net_diff variable that had been previously set correctly based on the hash target.

A fix is a little tricky because the code is so convoluted to handle both stratum and solo which do thing differently.

**Comment by JayDDee** [comment] 2021-06-25 18:14
I found a simple solution, declare a local net_diff in get_mininginfo. This will override the global net_diif preventing it
from being overwritten. The get_mining info log will continue to display the data from the previous block but the
share difficulty test will use a net diff derived from the actual hash target.

The code is still a mess but this solution doesn't make it any messier.

**Comment by JayDDee** [comment] 2021-06-26 16:50
cpuminer-opt-3.16.5 is released which hopefully fixes this issue.

The major change is to ensure the diff calculated from the target supplied in the work is used by the miner because
the diff in mininginfo is from the previous block. Previously when the diff changes the miner was one block behind updating
to the new diff.

Aside from confirming that solved blocks are no longer reported as only accepted when the diff i slower than the previous
block, The calculated diff should be compared with mininginfo for the same block to ensure they agree and to what level
of precision. Please run a test with -D to compare the diff in the New Block logs vs the Mininginfos log for a few blocks
with diffrerent diffs.

I also fixed a formatting issue in the share result log when --no-color is used, it was trying to format a null pointer instead
of a string with a null char.

**Comment by YetAnotherRussian** [comment] 2021-06-27 16:01
Seems to be OK for now. Will check the regular cli output as well (without --debug).
[cpuminer_log6.zip](https://github.com/JayDDee/cpuminer-opt/files/6721862/cpuminer_log6.zip)

**Comment by JayDDee** [comment] 2021-06-27 16:35
Solved block #4 is the one that proves it now works. The previous block had a higher net diff than the submitted hash and
the new net diff for the block that was solved.

Thanks for finding this bug and testing the fix.

**Comment by YetAnotherRussian** [comment] 2021-06-27 18:58
Yep, regular mode is okay.

![4](https://user-images.githubusercontent.com/4670472/123556250-c974bc80-d792-11eb-9e09-3c1feedf2686.png)

**Comment by JayDDee** [comment] 2021-07-01 00:22
No problems reported, closing.

**Closed by JayDDee** 2021-07-01 00:22 UTC
