### ISSUE TITLE
Invalidextranonce2 size 

### ISSUE THREAD

**Issue by SupraryGood** [JayDDee/cpuminer-opt#406] opened 2023-11-04 09:21 UTC
Failed to get extranonce2_size
[2023-11-04 09:18:50] JSON-RPC call failed: (unknown reason)

eu.kmd.k1pool.com:6250

`./cpuminer -a yescrypt -u RJFnXLG5zPDtmcwJGKC9pJr8qPjo4kEutx -p c=KMD  -o stratum+tcp://eu.kmd.k1pool.com:6251 -t 8 --cpu-affinity 0x55`

What is wrong to use ?

**Comment by SupraryGood** [comment] 2023-11-04 10:28
What is wrong Hashrate 0 kh/s ... Everyting good :P

**Comment by JayDDee** [comment] 2023-11-04 14:04
It's a pool issue, maybe it doesn't support extranonce, try with  --no-extranonce.

Aside from that your cpu-affinity only has 4 cpus for 8 threads, it should be 0x5555.

**Comment by SupraryGood** [comment] 2023-11-04 20:42
Working easy good now. But i missing token "teject reason: Invalid job id" in pool bsty. Meaby have wrong commend i cant sure for it [./cpuminer -a yescrypt -u YHV4yUZZSLB1XQF3dLq49HpkUWbxvY7NDi -p c=BSTY,zap=BSTY  -o stratum+tcp://yescrypt.eu.mine.zpool.ca:6233 -t 4 --cpu-affinity 0x5555]

**Comment by JayDDee** [comment] 2023-11-04 21:32
Invalid job id means stale work, they are caused by network latency and can't be entirely prevented.

Now your affinity is backward, 8 cpus for 4 threads. They should match, either `--threads 4 --cpu-affinity 0x55` or` --threads 8 --cpu-affinity 0x5555`. There should be the same number of bits set in the mask as there threads defined.

I don'r see any problems, just an inexperienced user.

**Comment by JayDDee** [comment] 2023-11-04 23:25
Closing the issue, have fun.

**Closed by JayDDee** 2023-11-04 23:25 UTC
